feat: Display a message when it not running on Windows runner

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -23,6 +23,13 @@ runs:
 # https://github.com/microsoft/winget-cli/issues/700#issuecomment-874084714
   using: composite
   steps:
+    - name: Check runner os
+      if: ${{ runner.os != 'Windows' }}
+      shell: bash
+      run: |
+        echo "[ERROR] This action only runs on Windows runner, Current runner: ${{ runner.os }}"
+        exit 1
+
     - name: Download Microsoft.UI.Xaml v2.8.6
       shell: powershell
       run: |
